### ISSUE TITLE
blocked by cors policy

### ISSUE THREAD

**Issue by bipindubey-technoark** [medartus/kahaki#2]
I am implementing this component is my project but it is giving following error

Access to fetch at 'https://www.npmjs.com/package/react-tiny-link' from origin 'http://localhost:3001' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by medartus** [comment]
You can't access to other website metadata from the front end due to CORS policy.
To avoid this issue, use Kahaki from your backend or use https://urlpreview.vercel.app/.
> https://urlpreview.vercel.app/api/v1/preview?url=https%3A%2F%2Fwww.npmjs.com%2Fpackage%2Freact-tiny-link

**Comment by bipindubey-technoark** [comment]
Ok will try this
Thanks @medartus 

> You can't access to other website metadata from the front end due to CORS policy.
> To avoid this issue, use Kahaki from your backend or use https://urlpreview.vercel.app/.
> 
> > https://urlpreview.vercel.app/api/v1/preview?url=https%3A%2F%2Fwww.npmjs.com%2Fpackage%2Freact-tiny-link
